apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-kafka
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cksdud1202a/wikipulse-lab.git
    targetRevision: main
    path: gitops/manifests/kafka
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
