#Strimzi 오퍼레이터 Helm으로 설치
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-strimzi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://strimzi.io/charts/
    chart: strimzi-kafka-operator
    targetRevision: 0.45.0
    helm:
      values: |
        watchNamespaces:
          - kafka  # kafka 네임스페이스만 감시 (watchAnyNamespace는 ClusterRole 권한 문제 발생)
  destination:
    server: https://kubernetes.default.svc
    namespace: strimzi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
